#!/usr/bin/env node
// Generates the iLEAD programme detail pages from one data file and one set of templates.
//
//   node ilead-programs/build.mjs          write chuong-trinh/<slug>/index.html and 404.html
//   node ilead-programs/build.mjs --check  exit 1 if the generated files are out of date
//
// The site is deployed as static files with no build step, so the generated pages are committed.
// Edit programs.json or templates/*.html, then run this script — never edit the output by hand.

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SITE_ROOT = join(HERE, '..');
const OUTPUT_DIR = join(SITE_ROOT, 'chuong-trinh');
const GENERATED_MARKER = '<!-- Generated by ilead-programs/build.mjs from programs.json. Do not edit by hand. -->';
const TOPIC_COUNT = 6;
const BENEFIT_COUNT = 4;
const SHARED_KEYS = ['eyebrow', 'subtitle', 'outcomeLabel', 'frameworkLabel', 'topicsHeading', 'benefitsHeading', 'audienceHeading', 'ctaLabel', 'backLabel', 'finalHeading'];
// Material Symbols used by the templates themselves (topic/benefit icons come from programs.json).
const TEMPLATE_ICONS = ['arrow_back', 'arrow_forward', 'groups', 'menu_book'];
const ICON_NAME = /^[a-z0-9_]+$/;

const read = path => readFileSync(join(HERE, path), 'utf8');
const normalize = text => text.replace(/\r\n/g, '\n');
const withMarker = html => html.replace(/^<!DOCTYPE html>\n/i, doctype => `${doctype}${GENERATED_MARKER}\n`);

// ---------------------------------------------------------------------------
// Tiny template engine: {{var}} (escaped), {{{var}}} (raw), {{#if x}}…{{else}}…{{/if}},
// {{#each list}}…{{/each}} with {{this}}, {{this.key}}, {{@num}} and {{@num2}} (zero-padded).
// Blocks do not nest inside blocks of the same kind. Unknown variables are errors.

const escapeHtml = value => String(value)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&#39;');

const TOKEN_RE = /\{\{#each ([\w.@]+)\}\}([\s\S]*?)\{\{\/each\}\}|\{\{#if ([\w.@]+)\}\}([\s\S]*?)(?:\{\{else\}\}([\s\S]*?))?\{\{\/if\}\}|\{\{\{\s*([\w.@]+)\s*\}\}\}|\{\{\s*([\w.@]+)\s*\}\}/g;

function lookup(scope, path) {
  const [head, ...rest] = path.split('.');
  let frame = scope;
  while (frame && !(head in frame)) frame = frame.__parent;
  if (!frame) return undefined;
  return rest.reduce((value, key) => (value == null ? undefined : value[key]), frame[head]);
}

function render(template, scope, source) {
  return template.replace(TOKEN_RE, (match, eachName, eachBody, ifName, ifBody, elseBody = '', rawName, varName) => {
    if (eachName) {
      const list = lookup(scope, eachName);
      if (!Array.isArray(list)) throw new Error(`${source}: {{#each ${eachName}}} is not a list`);
      return list.map((item, index) => render(eachBody, {
        __parent: scope,
        this: item,
        '@num': index + 1,
        '@num2': String(index + 1).padStart(2, '0')
      }, source)).join('');
    }
    if (ifName) return render(lookup(scope, ifName) ? ifBody : elseBody, scope, source);
    const name = rawName || varName;
    const value = lookup(scope, name);
    if (value === undefined || value === null) throw new Error(`${source}: missing value for {{${name}}}`);
    return rawName ? String(value) : escapeHtml(value);
  });
}

// ---------------------------------------------------------------------------
// Data validation — fail loudly so a typo never ships a half-empty page.

function validate(data) {
  const errors = [];
  const text = (value, where) => {
    if (typeof value !== 'string' || !value.trim()) errors.push(`${where} must be a non-empty string`);
  };

  text(data.site?.url, 'site.url');
  text(data.site?.brandName, 'site.brandName');
  text(data.site?.phone, 'site.phone');
  try { new URL(data.site?.url); } catch { errors.push('site.url must be an absolute URL'); }
  for (const key of SHARED_KEYS) text(data.shared?.[key], `shared.${key}`);

  if (!Array.isArray(data.programs) || !data.programs.length) errors.push('programs must be a non-empty list');
  const slugs = new Set();
  const orders = new Set();
  for (const [index, p] of (data.programs || []).entries()) {
    const where = `programs[${index}] (${p?.slug || 'no slug'})`;
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p.slug || '')) errors.push(`${where}.slug must be lowercase letters, digits and hyphens`);
    if (slugs.has(p.slug)) errors.push(`${where}.slug is duplicated`);
    slugs.add(p.slug);
    if (!Number.isInteger(p.order)) errors.push(`${where}.order must be an integer`);
    if (orders.has(p.order)) errors.push(`${where}.order is duplicated`);
    orders.add(p.order);
    for (const key of ['name', 'referenceOutcome', 'tagline', 'audience']) text(p[key], `${where}.${key}`);
    if (!/^#[0-9a-f]{6}$/i.test(p.accent || '')) errors.push(`${where}.accent must be a #RRGGBB colour`);
    if (!Array.isArray(p.topics) || p.topics.length !== TOPIC_COUNT) errors.push(`${where}.topics must have exactly ${TOPIC_COUNT} items`);
    else p.topics.forEach((t, i) => text(t, `${where}.topics[${i}]`));
    if (!Array.isArray(p.benefits) || p.benefits.length !== BENEFIT_COUNT) errors.push(`${where}.benefits must have exactly ${BENEFIT_COUNT} items`);
    else p.benefits.forEach((b, i) => text(b, `${where}.benefits[${i}]`));
    const iconList = (key, count) => {
      if (!Array.isArray(p[key]) || p[key].length !== count || !p[key].every(name => ICON_NAME.test(name))) {
        errors.push(`${where}.${key} must be ${count} Material Symbols icon names`);
      }
    };
    iconList('topicIcons', TOPIC_COUNT);
    iconList('benefitIcons', BENEFIT_COUNT);
    if (!p.banner || typeof p.banner !== 'object') {
      errors.push(`${where}.banner is required`);
    } else {
      text(p.banner.src, `${where}.banner.src`);
      text(p.banner.alt, `${where}.banner.alt`);
      if (!Number.isInteger(p.banner.width) || !Number.isInteger(p.banner.height)) errors.push(`${where}.banner.width/height must be integers`);
      if (p.banner.src && !existsSync(join(SITE_ROOT, p.banner.src))) errors.push(`${where}.banner.src not found: ${p.banner.src}`);
    }
  }
  if (errors.length) throw new Error(`programs.json is invalid:\n  - ${errors.join('\n  - ')}`);
}

// ---------------------------------------------------------------------------

const lowerFirst = text => text.charAt(0).toLocaleLowerCase('vi') + text.slice(1);

function assetVersion() {
  const hash = createHash('sha1');
  for (const file of ['uploads/ilead-program.css', 'uploads/ilead-nav.js']) hash.update(readFileSync(join(SITE_ROOT, file)));
  return hash.digest('hex').slice(0, 8);
}

// 404.html is served for missing URLs at any depth, so relative links need a <base>. It points at
// the part of the path before /chuong-trinh/ (or the project folder on *.github.io), else the root.
const NOT_FOUND_BASE_SCRIPT = `<script>(function(){var p=location.pathname,i=p.indexOf('/chuong-trinh/'),b='/';if(i>=0){b=p.slice(0,i+1);}else if(/\\.github\\.io$/.test(location.hostname)){var s=p.split('/')[1];if(s){b='/'+s+'/';}}var e=document.createElement('base');e.href=b;document.head.appendChild(e);})();</script>`;

function buildPages(data) {
  const layout = read('templates/layout.html');
  const programTemplate = read('templates/program.html');
  const notFoundTemplate = read('templates/not-found.html');
  const version = assetVersion();
  const programs = [...data.programs].sort((a, b) => a.order - b.order);
  const pages = new Map();
  // Load only the icons actually used (Google Fonts requires the names sorted alphabetically).
  const icons = [...new Set([...TEMPLATE_ICONS, ...programs.flatMap(p => [...p.topicIcons, ...p.benefitIcons])])].sort();
  const iconFontUrl = `https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:FILL@1&amp;icon_names=${icons.join(',')}&amp;display=block`;

  for (const program of programs) {
    const root = '../../';
    const canonical = new URL(`chuong-trinh/${program.slug}/`, data.site.url).href;
    const title = `${program.name} – Tiếng Anh tiểu học ${program.referenceOutcome} | ${data.site.brandName}`;
    const description = `${program.tagline}. Phù hợp với ${lowerFirst(program.audience)}`;
    // "iLEAD 1" -> brand word and level number styled separately, as in the design.
    const numbered = /^(.*?)\s+(\d+)$/.exec(program.name);
    const nameHtml = numbered
      ? `<span class="lp-title-brand">${escapeHtml(numbered[1])}</span> <span class="lp-title-num">${escapeHtml(numbered[2])}</span>`
      : `<span class="lp-title-brand">${escapeHtml(program.name)}</span>`;
    // The tagline is shown as a headline + a second line, split at the first " – ".
    const dash = program.tagline.indexOf(' – ');
    const taglineLead = dash > 0 ? program.tagline.slice(0, dash) : program.tagline;
    const taglineRest = dash > 0 ? program.tagline.slice(dash + 3) : '';
    const topicItems = program.topics.map((text, i) => ({ text, icon: program.topicIcons[i], tone: (i % 6) + 1 }));
    const benefitItems = program.benefits.map((text, i) => ({ text, icon: program.benefitIcons[i] }));
    const headMeta = [
      `<link rel="canonical" href="${escapeHtml(canonical)}">`,
      `<meta property="og:type" content="website">`,
      `<meta property="og:locale" content="vi_VN">`,
      `<meta property="og:title" content="${escapeHtml(title)}">`,
      `<meta property="og:description" content="${escapeHtml(description)}">`,
      `<meta property="og:url" content="${escapeHtml(canonical)}">`,
      `<meta property="og:image" content="${escapeHtml(new URL(program.banner.src, data.site.url).href)}">`
    ].filter(Boolean).join('\n');

    const scope = {
      ...program, site: data.site, shared: data.shared, root, nameHtml, iconFontUrl,
      taglineLead, taglineRest, topicItems, benefitItems
    };
    const content = render(programTemplate, scope, 'templates/program.html');
    const html = render(layout, {
      ...scope,
      page: 'program',
      htmlAttrs: ` data-ilead-slug="${escapeHtml(program.slug)}"`,
      baseTag: '',
      title,
      description,
      headMeta,
      assetVersion: version,
      content
    }, 'templates/layout.html');
    pages.set(join(OUTPUT_DIR, program.slug, 'index.html'), withMarker(html));
  }

  const notFoundScope = { site: data.site, shared: data.shared, programs, root: './', iconFontUrl };
  const notFoundContent = render(notFoundTemplate, notFoundScope, 'templates/not-found.html');
  const notFound = render(layout, {
    ...notFoundScope,
    page: 'not-found',
    htmlAttrs: '',
    baseTag: NOT_FOUND_BASE_SCRIPT,
    title: `Không tìm thấy trang | ${data.site.brandName}`,
    description: 'Trang bạn tìm không tồn tại hoặc đã được đổi địa chỉ.',
    headMeta: '<meta name="robots" content="noindex">',
    assetVersion: version,
    content: notFoundContent
  }, 'templates/layout.html');
  pages.set(join(SITE_ROOT, '404.html'), withMarker(notFound));

  return pages;
}

// Generated programme folders that are no longer in programs.json (only ones carrying the marker).
function staleProgramFiles(pages) {
  if (!existsSync(OUTPUT_DIR)) return [];
  return readdirSync(OUTPUT_DIR, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => join(OUTPUT_DIR, entry.name, 'index.html'))
    .filter(file => !pages.has(file) && existsSync(file) && readFileSync(file, 'utf8').includes(GENERATED_MARKER));
}

// The home page cards are hand-written in index.html; warn if one does not point at its page.
function checkHomeLinks(programs, home) {
  return programs
    .filter(p => !home.includes(`href="chuong-trinh/${p.slug}/"`))
    .map(p => `index.html has no card link to chuong-trinh/${p.slug}/`);
}

// index.html loads the same ilead-nav.js; keep its ?v= in step with the generated pages, because
// browsers reuse cached scripts on back/forward navigations.
const HOME_SCRIPT_RE = /(<script src="uploads\/ilead-nav\.js\?v=)([^"]*)(")/;
function syncHomeScriptVersion(home, version) {
  if (!HOME_SCRIPT_RE.test(home)) throw new Error('index.html does not load uploads/ilead-nav.js?v=…');
  return home.replace(HOME_SCRIPT_RE, `$1${version}$3`);
}

function main() {
  const check = process.argv.includes('--check');
  const data = JSON.parse(read('programs.json'));
  validate(data);
  const pages = buildPages(data);
  const stale = staleProgramFiles(pages);
  const homeFile = join(SITE_ROOT, 'index.html');
  const home = readFileSync(homeFile, 'utf8');
  const syncedHome = syncHomeScriptVersion(home, assetVersion());
  const warnings = checkHomeLinks(data.programs, home);
  const rel = file => relative(SITE_ROOT, file).replace(/\\/g, '/');

  if (check) {
    const outdated = [...pages].filter(([file, html]) => !existsSync(file) || normalize(readFileSync(file, 'utf8')) !== normalize(html)).map(([file]) => rel(file));
    if (syncedHome !== home) outdated.push('index.html (ilead-nav.js ?v=)');
    warnings.forEach(w => console.warn(`warning: ${w}`));
    if (outdated.length || stale.length) {
      outdated.forEach(f => console.error(`out of date: ${f}`));
      stale.forEach(f => console.error(`stale: ${rel(f)}`));
      console.error('Run: node ilead-programs/build.mjs');
      process.exit(1);
    }
    console.log(`OK: ${pages.size} generated files are up to date.`);
    return;
  }

  for (const [file, html] of pages) {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, html);
    console.log(`wrote ${rel(file)}`);
  }
  for (const file of stale) {
    rmSync(dirname(file), { recursive: true });
    console.log(`removed ${rel(dirname(file))}`);
  }
  if (syncedHome !== home) {
    writeFileSync(homeFile, syncedHome);
    console.log('updated index.html (ilead-nav.js ?v=)');
  }
  warnings.forEach(w => console.warn(`warning: ${w}`));
}

try {
  main();
} catch (error) {
  console.error(error.message);
  process.exit(1);
}
